version: "3.8"
services:
  lv-web-fe:
    image : lalindrait/lvrocky91:1.1
    ports: 
      - 8000:80
    volumes:
      - lv_vol_01:/vol_01
      - lv_vol_01:/vol_02
      - /docker/html:/web
    networks:
      - lv-web-dmz
      - lv-app-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
          pids: 10
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  mysql-db:
    image : mysql:latest
    volumes:
      - lv_db_data:/var/lib/mysql
    networks:
      - lv-app-net
    deploy:
      restart_policy:
        condition: none
    secrets:
      - mysql_user_password
      - mysql_root_password
    environment:
      MYSQL_DATABASE : lvapp-db
      MYSQL_USER: lvuser
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password


volumes:
  lv_vol_01:
    driver: local
  lv_vol_02:
    driver: local
  lv_db_data:
    driver: local

networks:
  lv-web-dmz:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.100.100.0/24"
  lv-app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.100.101.0/24"

secrets:
  mysql_user_password:
    file: ./secrets/mysql_user_pass.txt
  mysql_root_password:
    file: ./secrets/mysql_root_pass.txt




